### ISSUE TITLE
Data orientation issue

### ISSUE THREAD

**Issue by ilkayisik** [ofgulban/segmentator#36]
Data shows up in unorthodox orientations.
I suggest to assign some buttons to rotate it instead of adding header information.

**Comment by virtualmarioe** [comment]
I agree, the buttos can be useful, however, the buttons can also be complete it with labels such as SAG, anterior, superior/ventral etc. These labels can be particularly useful, for example, when someone wants to use anatomical landmarks to guide the inclusion of given structures in the mask.

Additionally, for clarity reasons would be useful to add a title in the right panel, for example, 'Anatomical view'.

**Comment by ofgulban** [comment]
I am a little hesitant to put orientation labels in the interface because Segmentator can be used not only for brains but for any sort of 3D data (knee, spine, other materials etc.) and in addition due to the extra hassle of reading/displaying the headers in different conventions (radiological/neurological) correctly.

I would prefer to leave setting the data orientation to the user maybe with rotate buttons.

@MSchnei, what do you think?

**Comment by virtualmarioe** [comment]
Valit point, I was mainly thinking about brain applications although it still aplies to other anatomical structures but not to other materials. Additionally, the point about the implementation is fair. That's something it can be leave to indivual user customizations.

**Comment by ofgulban** [comment]
@ilkayisik @virtualmarioe I have added a rotate button in version 1.3.0 (currently in devel branch) right under cycle. 
![animated](https://user-images.githubusercontent.com/4668327/30822949-eb23ee6a-a22a-11e7-9eee-9e8e79711e36.gif)
