### ISSUE TITLE
Stripes in the 2D histogram

### ISSUE THREAD

**Issue by ilkayisik** [ofgulban/segmentator#37]
They are appearing because of the default intensity scaling value when the data has an integer range less than 500. 
Scaling can be controlled when initialising the segmentator with the argument ```--scale``` but I think it will be good to explain it somewhere. Or you can find a way to automatically adjust for it.

**Comment by ofgulban** [comment]
I think we can have a wiki page about this issue to explain when to use the ```--scale``` argument.

One example is Brainvoyager's vmr files. Which have even less than uint8 precision. In this format the gray values are only ranged from 0 to 225.
The *stripes* caused by Segmentator's default scaling parameter (500) can be removed by having ```--scale 225``` argument.

I will update this issue once we have prepared the wiki page.

**Comment by ofgulban** [comment]
The wiki page is ready:
https://github.com/ofgulban/segmentator/wiki/Case-III%3A-Freesurfer
