### ISSUE TITLE
new matplotlib version

### ISSUE THREAD

**Issue by ingo-m** [ofgulban/segmentator#42]
Due to the new matplotlib version (2.0.0) the layout of segmentator has changed a bit (this is NOT a bug, it works fine - just wanted to give everyone a heads-up). However, I have the impression that the 'sector mask' (or whatever name the pacman/circle selector now has) is moving a bit slower (but I'm not absolutely sure about that - please check yourself).

Happy segmentations

![new_matplotlib](https://cloud.githubusercontent.com/assets/10960892/22327871/b761ee04-e3b9-11e6-83e3-0fdaff7c82dc.png)

**Comment by ofgulban** [comment]
Thanks @ingo-m it is good to know. Another reason to change the matplotlib interface, I think it served its purpose. I was considering [pyqtgraph](http://www.pyqtgraph.org/) for the new interface but probably it will take some time to implement.

In the meanwhile you can use --scale parameter to change the 2D histogram resolution to a lower one (eg. 300 instead of 500) to make the sector mask faster.

**Comment by ofgulban** [comment]
Actually, thinking about this a bit more, it might still be valuable to fix matplotlib 2 issues in the short term. I will have a look into this in more detail, for now it seems that ncut mode is effected the most.

**Comment by ofgulban** [comment]
I had a look into this and decided to wait until matplotlib 2.1 release. It seems that there were some issues with alpha channels and they are addressed. In the meanwhile we should stick with matplotlib 1.5.3

**Comment by ofgulban** [comment]
Well, after having a look second time, I have figured what needs to be changed for matplotlib 2.0 compatibility. Changes are incorporated to segmentator v1.3.0. Earlier matplotlib versions are not compatible anymore.
